// SPDX-License-Identifier: MIT
// Generated by scripts/nums.py — do not edit.
pragma solidity ^0.8.28;

/// @title CanaryTargets
/// @notice Public keys guarded by the quantum canary registry.
/// Ladder targets L1 (secp160r1), L2 (P-192) and L3 (P-224) are affine points, as are the
/// R1 (P-256) coordinates; K1 (secp256k1) is the Ethereum address of the key.
library CanaryTargets {
    struct Targets {
        bytes32 l1x;
        bytes32 l1y;
        bytes32 l2x;
        bytes32 l2y;
        bytes32 l3x;
        bytes32 l3y;
        address k1;
        bytes32 r1x;
        bytes32 r1y;
    }

    /// @notice Nothing-up-my-sleeve points: x = SHA-256("QANARY-NUMS-V1/" || name || ctr) mod p, even y.
    /// Nobody knows their discrete logarithms.
    function nums() internal pure returns (Targets memory) {
        return Targets({
            l1x: 0x00000000000000000000000025a797c6e350f6acdf588ff1564f051529292a48,
            l1y: 0x000000000000000000000000a16ea01f5c22ad0e000129d8912a8306c5b0b83e,
            l2x: 0x000000000000000004b501df22b9432fe0b9a14a096b5cd2faaef69730d6fdd3,
            l2y: 0x0000000000000000705401ce8bedd134332f0d495e04034399de092756b0a468,
            l3x: 0x0000000096a5f9c939ee22c559004d07031b50685f33fb64e0d0f1c7806bc7ee,
            l3y: 0x00000000ade8dc437f3fcb5191b0136918a21b01facf59e1985d4ce641be0a26,
            k1: 0x4b1471AA57db46685dff51791e0941A61ccE5403,
            r1x: 0xd5793fe330652fd98158c57ce2d8f975badccc21669fb5c3a6cd9de3db92b78b,
            r1y: 0x3174cab4757db09e96ad147906f0743f0d0100bd575f3138cd6fb3b3a9432f18
        });
    }

    /// @notice Drill keys with published private keys d = SHA-256("QANARY-DRILL-V1/" || name) mod n.
    /// For rehearsing claims only; they guard nothing.
    function drill() internal pure returns (Targets memory) {
        return Targets({
            l1x: 0x00000000000000000000000069850ca04019ae4f2d4e5ac7677af4ffb6a6428c,
            l1y: 0x000000000000000000000000306b95702654c9a7579c95781019d447b74796f7,
            l2x: 0x00000000000000009c26b1ea168ddc297253ca73e3eedcfce53fc9d6ffb113f0,
            l2y: 0x0000000000000000266b15d4932dc38250acad1bc40dd6d6bcb58a55a701d5f6,
            l3x: 0x00000000705181343f9bb58d136eab53f3ee0803a69687a54527a42ee618f68a,
            l3y: 0x00000000a99dfb8f04e1bb05d4b0c53392a26ef4378b761c7d45b228a9596b29,
            k1: 0xD56fbAE6f6e1a0f7790d279CE86fC9638EE02184,
            r1x: 0x72f54bb03b67b6d47db8e14b042187978aab374dae6cafebbbc71c35e6da25a3,
            r1y: 0x4afc41074a85780e4126cfe88609346beb27cf5f59688436b8013089db3c4bc6
        });
    }
}
